require_relative 'reload'
require_relative 'colorea'
require_relative 'Player'
require_relative 'initializer.rb'
require_relative 'run_controller'
require_relative 'it'
require_relative 'goose'
require_relative 'sitter'
require_relative 'arm'
require_relative 'ayuke'
require_relative 'kamehame'
require_relative 'doublehats'
require_relative 'player_factory'
require_relative 'default_order'
require_relative 'random_order'
require_relative 'game_run'
require_relative 'it_first_order'



require 'byebug'